---
- name: Add ingress Helm repository
  kubernetes.core.helm_repository:
    name: ingress
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Install ingress-nginx helm chart
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress/ingress-nginx
    chart_version: "{{ ingress_nginx_chart_version }}"
    release_namespace: ingress-nginx
    create_namespace: true
    wait: true
    values:
      controller:
        minReadySeconds: 0
        progressDeadlineSeconds: 600