---
- name: Add Calico Helm repository
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: https://projectcalico.docs.tigera.io/charts
    state: present

- name: Install Calico helm chart
  kubernetes.core.helm:
    name: calico
    chart_ref: projectcalico/tigera-operator
    release_namespace: tigera-operator
    create_namespace: true
    wait: true

- name: Wait for Calico pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: calico-system
    wait: true
    wait_condition:
      type: Ready
      status: "True"
