---
- name: Unhold kubeadm, kubelet and kubectl packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
    - kubeadm
    - kubelet
    - kubectl

- name: Download Kubernetes GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ kube_short_version }}/deb/Release.key
    dest: /tmp/kubernetes.key
    mode: "0644"

- name: Import Kubernetes GPG key
  ansible.builtin.shell: |
    set -o pipefail
    cat /tmp/kubernetes.key | gpg --dearmor --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    executable: /bin/bash
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Remove Kubernetes repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg]
      https://pkgs.k8s.io/core:/stable:/v{{ kube_short_version }}/deb/ /
    state: present
    filename: kubernetes

- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade kubeadm, kubelet, and kubectl packages
  ansible.builtin.apt:
    name:
      - kubelet={{ kube_version }}*
      - kubeadm={{ kube_version }}*
      - kubectl={{ kube_version }}*
    state: present
    update_cache: true
    force: true
    dpkg_options: 'force-confdef,force-confold'
    force_apt_get: true
    allow_change_held_packages: true

- name: Hold kubeadm, kubelet, and kubectl versions
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubelet
    - kubectl
