---
- name: Gathering facts
  ansible.builtin.setup:

- name: Include setup tasks
  ansible.builtin.include_tasks:
    file: setup.yml
  when:
    - role_action | default("setup") == "setup"
    - kube_vip_enabled

- name: Include reset tasks
  ansible.builtin.include_tasks:
    file: reset.yml
    apply:
      become: false
  when:
    - role_action is defined and role_action == "reset"
    - kube_vip_enabled
