---
- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  when: role_action | default("setup") == "setup"

- name: Include reset tasks
  ansible.builtin.include_tasks: reset.yml
  when: role_action is defined and role_action == "reset"
