---
- name: Add cilium helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Install Cilium Helm chart
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "{{ cni_cilium_version }}"
    release_namespace: kube-system
    wait: true
