---
- name: Gathering facts
  ansible.builtin.setup:

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  when:
    - csi_plugin == "longhorn"
    - role_action is defined and role_action == "setup"

- name: Include reset tasks
  ansible.builtin.include_tasks: reset.yml
  when:
    - csi_plugin == "longhorn"
    - inventory_hostname in groups['workers']
    - role_action is defined and role_action == "reset"
