---
- name: Set deleting-confirmation-flag in longhorn-default-setting
  kubernetes.core.k8s:
    name: longhorn-default-setting
    namespace: longhorn
    kind: ConfigMap
    definition:
      data:
        default-setting.yaml: |-
          priority-class: longhorn-critical
          disable-revision-counter: true
          deleting-confirmation-flag: "true"
    merge_type: strategic-merge
  become: false
  delegate_to: "{{ groups['control_planes'][0] }}"
  run_once: true

- name: Uninstall longhorn helm chart
  kubernetes.core.helm:
    name: longhorn
    namespace: longhorn
    state: absent
    wait: true
  become: false
  delegate_to: "{{ groups['control_planes'][0] }}"
  run_once: true

- name: Remove longhorn helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    state: absent
  become: false
  delegate_to: "{{ groups['control_planes'][0] }}"
  run_once: true