---
- name: Install longhorn dependencies
  ansible.builtin.include_tasks:
    file: "{{ ansible_os_family | lower }}.yml"
  when: 
    - inventory_hostname in groups['workers']
    - ansible_os_family in ["Debian", "RedHat"]

- name: Enable and start iscsid service
  ansible.builtin.systemd:
    name: iscsid
    enabled: true
    state: started
  when: 
    - inventory_hostname in groups['workers']
    - ansible_os_family in ["Debian", "RedHat"]

- name: Add longhorn Helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
  become: false
  delegate_to: "{{ groups['control_planes'][0] }}"
  run_once: true
  register: longhorn_repo

- name: Install longhorn helm chart
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_chart_version }}"
    release_namespace: longhorn
    create_namespace: true
    wait: true
  become: false
  delegate_to: "{{ groups['control_planes'][0] }}"
  run_once: true
  when: longhorn_repo.changed