---
- name: Pull images used by kubeadm
  ansible.builtin.shell: |
    kubeadm config images pull --kubernetes-version=v{{ kube_version }}
  args:
    executable: /bin/bash
  register: pull_images
  changed_when: pull_images.rc == 0

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/kubernetes/manifests

- name: Prepare kubeadm init config
  ansible.builtin.template:
    src: init-config.yml.j2
    dest: "/home/{{ ansible_user }}/kubeadm-init-config.yml"
    mode: "0600"
    force: true
  register: kubeadm_init_config
  changed_when: kubeadm_init_config.changed

- name: Initialize Kubernetes cluster
  ansible.builtin.shell: |
    set -o pipefail
    kubeadm init --config="/home/{{ ansible_user }}/kubeadm-init-config.yml" \
                 --upload-certs | tee "/home/{{ ansible_user }}/kubeadm-init.log"
  args:
    executable: /bin/bash
  register: init_cluster
  changed_when: init_cluster.rc == 0
  failed_when: init_cluster.rc != 0
