---
- name: Gathering facts
  ansible.builtin.setup:

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  when:
    - role_action is defined and role_action == "setup"
    - container_runtime | default("containerd") == "containerd"

- name: Include reset tasks
  ansible.builtin.include_tasks: reset.yml
  when:
    - role_action is defined and role_action == "reset"
    - container_runtime | default("containerd") == "containerd"
