---
- name: Setup containerd runtime
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family in ["Debian", "RedHat"]

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Generate default containerd configuration
  ansible.builtin.command: containerd config default
  register: containerd_config
  changed_when: false

- name: Write containerd configuration
  ansible.builtin.copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml
    mode: "0644"

- name: Update containerd sandbox image
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: "sandbox_image = \"registry.k8s.io/pause:3.8\""
    replace: "sandbox_image = \"registry.k8s.io/pause:3.10\""

- name: Configure containerd to use systemd cgroup driver
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: "SystemdCgroup = false"
    replace: "SystemdCgroup = true"

- name: Enable and restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
    daemon_reload: true
